package warehouse.shared.transferObjects;

public enum EventType {
    SUCCESSFUL_SHOP_CREATION,
    UNSUCCESSFUL_SHOP_CREATION,
    ALL_SHOPS_LIST,
    ALL_USERS_LIST,
    SUCCESSFUL_SHOP_DELETION,
    SHOP_DELETED,
    SHOP_DELETE_ERROR
}
